import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
  team,
  analytics,
}: {
  children: React.ReactNode;
  team: React.ReactNode;
  analytics: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="bg-white text-black dark:bg-black dark:text-white">
            {/* 加载平行路由 */}
            {team}
            {children}
            {analytics}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
